language: cpp
sudo: false

# Build matrix:
python:
- "2.7"
- "3.5"
compiler:
- gcc
- clang
env:
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=0
- BUILD_METALIBS=OFF COMPOSITE_SOURCE_LIMIT=0
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=30
- BUILD_METALIBS=OFF COMPOSITE_SOURCE_LIMIT=30

# Remove some combinations from the build matrix, to be nice to Travis:
matrix:
  exclude:
  - python: "2.7"
    compiler: gcc
  - python: "2.7"
    env: BUILD_METALIBS=OFF COMPOSITE_SOURCE_LIMIT=0
  - python: "2.7"
    env: BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=30

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.7
    - g++-4.7
    - bison
    - flex
    - libavcodec-dev
    - libavformat-dev
    - libavresample-dev
    - libavutil-dev
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libjpeg-dev
    - libode-dev
    - libopenal-dev
    - libpng-dev
    - libssl-dev
    - libswscale-dev
    - libvorbis-dev
    - libx11-dev
    - libxcursor-dev
    - libxrandr-dev
    - nvidia-cg-toolkit
    - python-dev
    - python3-dev
    - python-virtualenv
    - zlib1g-dev
    - fakeroot

# clean up remnants of makepanda
before_install:
- mv makepanda/test_imports.py .
- makepanda/selfdestruct.py --yes

install:
- virtualenv venv && source venv/bin/activate
- pip install pytest

before_script:
- mkdir built
- cd built

script:
- cmake -DHAVE_GTK2=NO -DBUILD_METALIBS=$BUILD_METALIBS -DCOMPOSITE_SOURCE_LIMIT=$COMPOSITE_SOURCE_LIMIT .. 
- make -j4

after_script:
- ../test_imports.py
- pytest ../tests

notifications:
  irc:
    channels:
    - "chat.freenode.net#panda3d"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
